name: Upload tarball

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Tarball
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Version Packages Using Changesets
        id: version
        run: |
          yarn changeset version
          echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> "$GITHUB_ENV"

      - name: Build Packages as Tarballs
        id: build
        run: |
          mkdir -p built-packages
          yarn workspaces foreach --no-private --verbose \
            exec yarn pack --filename "../built-packages/\${npm_package_name}-\${npm_package_version}.tgz"

      - name: Upload Built Packages as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: built-packages/
